In [1]:
#matrix operastions(using vectorization) and transformation using python
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

C = A+B
D = A-B
E = A*B
F = np.dot(A,B)
A_transpose = A.T

print("Addition:")
print(C)
print("Subtraction:")
print(D)
print("element wise multiplication:")
print(E)
print("matrix multiplication:")
print(F)
print("Transpose:")
print(A_transpose)


Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]
element wise multiplication:
[[ 5 12]
 [21 32]]
matrx multiplication:
[[19 22]
 [43 50]]
Transpose:
[[1 3]
 [2 4]]


In [3]:
#with SVD
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT = np.linalg.svd(X)
n_components = 2
X_reconstructed = np.dot(U[:, :n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Original Matrix:")
print(X)
print("Reconstructed Matrix (with reduced dimensions):")
print(X_reconstructed)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reconstructed Matrix (with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
